### ISSUE TITLE
Jenkins.getInstance().getRootUrl() returns null when running jenkins in a docker container with custom javakeystore mapped

### ISSUE THREAD

**Issue by Lars-Jakobsen-3Shape** [Argelbargel/gitlab-branch-source-plugin#100]
We are running a jenkins master in a docker image using jcasc where if the jenkins base url is not set then the following line will return null, even if the url is derived fine when viewing settings through jenkins UI.

https://github.com/Argelbargel/gitlab-branch-source-plugin/blob/24ce26fd5aeeab1ed25ab73bd3d81d13d99ea82c/src/main/java/argelbargel/jenkins/plugins/gitlab_branch_source/hooks/GitLabSCMWebHookListener.java#L80

seems related to a similar issue on another plugin https://github.com/nishio-dens/bitbucket-pullrequest-builder-plugin/issues/19

The impact is minimal as you won't hit this exception if the url is correctly set in jcasc

**Comment by Argelbargel** [comment]
Hi. Could you try if the new gitlab-branch-source-plugin (https://plugins.jenkins.io/gitlab-branch-source) fixes this issue? As the company i work for is itself switching to that plugin, i most probably will not make any changes the the code of this plugin (not that i've spent much time on it in the past year in any case :-/)

**Comment by Lars-Jakobsen-3Shape** [comment]
Hi

Thanks for the reply, yeah we already switched to that and even contributed I believe.

BR
Lars
