### ISSUE TITLE
Plugin triggers all branches if only one received push event

### ISSUE THREAD

**Issue by Tibor17** [Argelbargel/gitlab-branch-source-plugin#101]
@Argelbargel 
The problem is that all branches run the build whenever a commit went to the only one branch.
Is it understandable or should I post pictures with configuration.
Have you noticed this issue in your environment?
I am using Jenkins 2.150.3 and latest versions of prerequisite plugins.

**Comment by Tibor17** [comment]
@Argelbargel 
@paulerickson 
@lautou 
@ilushka85 
@rpannek 
I am wondering you are using this plugin successfully I have a permanent problem with executing branches. If I commit to one, all branches execute their build in particular project. This is wrong and the only one branch should execute the build. I do not use webhooks but 1 minute times as configured in GUI for this plugin in Jenkins. Do you have the same experiences. Or you had? How should I fix it?

**Comment by rpannek** [comment]
Hm we don't have this exact problem, the only problem we have right now is that branch-builds and mr-builds are displayed in the same tab, where they were displayed in different ones before. But we do triger builds from Gitlab with the webhook and not by time.

**Comment by Tibor17** [comment]
@rpannek 
@Argelbargel 
I am trying to isolate the issue two weeks. Changing the config and committing.
Now I found the root cause.
The problem was with attached `Jenkins Libraries`.
This plugin does not `remember` the previous commit hash of Jenkins Libraries and it still `thinks` it is a new and thus all the branches are rebuilt. Of course I do not commit to Jenkins Libraries. They stay intact two weeks. We only commit to our production branches.

**Comment by paulerickson** [comment]
Whoa, that sounds awful.  I have it manage webhooks (and recommend it) so I don't get this all the time. I do have it set to scan every day, if we're thinking of the same setting, and it does rebuild the world.  I figured this was just to detect Jenkinsfiles in new projects or catch up in case of missed events.  It didn't really occur to me that it should keep track like my old polling freestyle jobs did, but that would be great.

**Comment by Tibor17** [comment]
This awful behavior still presents when without Jenkins Libraries. We will check it out with webhooks.
@paulerickson How you configured one webhook for organization `org` (http://gitlab-server/org/repo)? We have only possibility to add a webhook per repository `repo` (http://gitlab-server/org/repo) in GitLab.

**Comment by ilushka85** [comment]
We are still using it and do not have this issue.  Does anyone know if the regular gitlab plugin now properly supports merge request builds for multi branch?

**Comment by deckrider** [comment]
Possibly caused by:

https://github.com/Argelbargel/gitlab-branch-source-plugin/issues/45

**Comment by Argelbargel** [comment]
Hi. Could you try if the new gitlab-branch-source-plugin (https://plugins.jenkins.io/gitlab-branch-source) fixes this issue? As the company i work for is itself switching to that plugin, i most probably will not make any changes the the code of this plugin (not that i've spent much time on it in the past year in any case :-/)
