### ISSUE TITLE
Releasing GitLab Branch Source Plugin to Jenkins

### ISSUE THREAD

**Issue by baymac** [Argelbargel/gitlab-branch-source-plugin#105]
Hi all,

I am accepted to Google Summer of Code 2019 under Jenkins and my project is based on adding Multibranch Pipeline Support to GitLab. 

Generally the SCM plugins are divided into 3 separate plugins, namely:

1) SCM-api-plugin: For wrapping <scm> API into a plugin

2) SCM-plugin: For build triggers, auth and webhooks management

3) SCM-branch-source-plugin: For branches, MRs, tags indexing and build for all jobs

e.g. github-api-plugin, github-plugin, github-branch-source-plugin

Since, GitLab does not have such an api-plugin we decided to choose an appropriate Java API for GitLab and wrap it into a plugin. GitLab API Plugin has been released to Jenkins Plugins Centre: https://plugins.jenkins.io/gitlab-api

Find GitLab API Repository here: https://github.com/jenkinsci/gitlab-api-plugin

The reasons for choosing a gitlab4j API is mentioned in the wiki page: https://wiki.jenkins.io/display/JENKINS/GitLab+API+Plugin

Our project plan is to modify the `gitlab-plugin` to depend on this new api-plugin and also to develop the `gitlab-branch-source-plugin` to support this new api-plugin.

For more details, my proposal can be found here: https://docs.google.com/document/d/1YpuCC129U8KPXAwiXRXQ_4XWuLursPGl3rzQjz43-CY/edit?usp=sharing 

Our plan right now:

1) Develop Kohsuke's GitLab Branch Source Plugin - https://github.com/jenkinsci/gitlab-branch-source-plugin. 

2) Take inspiration from your codebase and give you credits

3) Collaborate with contributors of this repository for code contributions, code reviews, insights etc.

What do you think about this idea? We can work together to get it released to Jenkins Official Update Center soon.

Reporting this upon suggestion of @grfullerton 
https://github.com/jenkinsci/gitlab-plugin/issues/499#issuecomment-479986870

**Comment by Argelbargel** [comment]
@baymac: That sounds just great. While "my" plugin works for me and the company i work for and - not least thanks to their contributions - for some others, i've never found the time to maintain it properly after the initial release. Not to speak of the plan to integrate this with the gitlab-plugin which did not get over the stage of some initial planning...

Thus i'd be grateful if you're project succeeds and we'll have a well maintained, official plugin and happy to help if i can.

**Comment by baymac** [comment]
Hi @Argelbargel and other users,

I have made some progress in the development of GitLab Branch Source Plugin. The source code can be found [here](https://github.com/jenkinsci/gitlab-branch-source-plugin/). My version of GitLab BS Plugin took a lot of inspiration from your plugin and [`Gitea Plugin`](https://github.com/jenkinsci/gitea-plugin/).

Currently, we have an [Alpha release](https://github.com/jenkinsci/gitlab-branch-source-plugin/releases/tag/gitlab-branch-source-v0.0.4-SNAPSHOT). Also planning to cut a release soon to the Jenkins Update centre (possibly before next weekend). It depends on the progress we make in this week. There are a few bugs that needs attention, it would be great if I could help some help from your side. The issues are being tracked [here](https://issues.jenkins-ci.org/browse/JENKINS-58481?jql=project%20%3D%20JENKINS%20AND%20status%20%3D%20Open%20AND%20component%20%3D%20gitlab-branch-source-plugin).

One important feature is the webhooks support and I am working on this [pr](https://github.com/baymac/gitlab-branch-source-plugin/pull/25). Jenkins creates the webhook on GitLab Server but the implementation to receive post requests from GitLab Server is a WIP. I need some help here, if anyone is interested to contribute let's discuss.

If you are able to test the plugin from the Alpha release. Please give your review on what features can added/improved.

Btw the idea of our plugin is to have a codebase similar to the rest of <SCM> Branch Source Plugins. It will help a lot with the maintainence. I have implemented a lightweight version of [`GitLab Plugin`](https://github.com/jenkinsci/gitlab-plugin/) inside my plugin itself. Also depending on a new [`GitLab API Plugin`](https://github.com/jenkinsci/gitlab-api-plugin).

Thanks.

**Comment by baymac** [comment]
Hi @Argelbargel ,

Just rechecking if you would work with me to fix an issue currently I am facing with the web hook. I am unable to trigger any SCM Events. I would really appreciate if I can receive some kind of help with this. We are just one step away from making a stable release this week. Let me know. :)
