### ISSUE TITLE
Cant select Gitlab SCM source in multibranch pipeline

### ISSUE THREAD

**Issue by i386** [Argelbargel/gitlab-branch-source-plugin#18]
First of all - its AWESOME that this plugin exists! I am investigating how soon we can add it to Blue Ocean... got time to chat? Drop me a line at jdumay@cloudbees.com 

Ok, so heres an issue I found:

*Problem*
You should be able to pick the Gitlab Project `SCMSource` from the list of sources in the Multibranch Pipeline project type.

*Steps to reproduce*

1. Have the Gitlab plugin installed
2. Go to the dashboard and click `New Item`
3. Set a name then pick the `Multibranch Pipeline` item type
4. Click `Add source`
5. `Gitlab Project` should appear in this list but it doesn't 😢 

*Screencast*
![gitlab-scm-source-not-found](https://cloud.githubusercontent.com/assets/50156/25885864/405fc7cc-359e-11e7-9fa0-d2c1abaa7344.gif)

**Comment by Argelbargel** [comment]
Ok, i think i've understood now what needs to be done to make this work. As all the configuration is currently done in the navigator-class, this will take some time to properly modulize so that the configuration can also be done for a single scm-source, but im working on it...

**Comment by i386** [comment]
@Argelbargel awesome! Let us know if there is any way we can help :)

**Comment by Argelbargel** [comment]
Hi @i386, i just released a version (0.7-dev) that seems to work with multibranch-pipeline projects. While definitively not production-ready yet, it would be nice if you could test it out and give some feedback.

**Comment by smutel** [comment]
Hi. This feature is very interesting for me too. I can test 0.7 version also if you guide me where to find it. Thanks.

**Comment by Argelbargel** [comment]
@smutel you can download it here: https://github.com/Argelbargel/gitlab-branch-source-plugin/releases/tag/0.7-dev

**Comment by smutel** [comment]
Upgrade the plugin with version 0.7-dev.
Have this error #47 again.

Received message below about configuration: 
> MissingFieldException: No field 'includes' found in class 'argelbargel.jenkins.plugins.gitlab_branch_source.settings.GitLabSCMSourceSettings', MissingFieldException: No field 'excludes' found in class 'argelbargel.jenkins.plugins.gitlab_branch_source.settings.GitLabSCMSourceSettings', MissingFieldException: No field 'merged' found in class 'argelbargel.jenkins.plugins.gitlab_branch_source.settings.GitLabSCMBranchMonitorStrategy', MissingFieldException: No field 'unmerged' found in class 'argelbargel.jenkins.plugins.gitlab_branch_source.settings.GitLabSCMBranchMonitorStrategy', MissingFieldException: No field 'ignoreWIP' found in class 'argelbargel.jenkins.plugins.gitlab_branch_source.settings.GitLabSCMBranchMonitorStrategy', MissingFieldException: No field 'onlyMergeable' found in class 'argelbargel.jenkins.plugins.gitlab_branch_source.settings.GitLabSCMBranchMonitorStrategy', MissingFieldException: No field 'acceptMergeRequests' found in class 'argelbargel.jenkins.plugins.gitlab_branch_source.settings.GitLabSCMBranchMonitorStrategy', MissingFieldException: No field 'removeSourceBranch' found in class 'argelbargel.jenkins.plugins.gitlab_branch_source.settings.GitLabSCMBranchMonitorStrategy', MissingFieldException: No field 'merged' found in class 'argelbargel.jenkins.plugins.gitlab_branch_source.settings.GitLabSCMOriginMonitorStrategy', MissingFieldException: No field 'unmerged' found in class 'argelbargel.jenkins.plugins.gitlab_branch_source.settings.GitLabSCMOriginMonitorStrategy', MissingFieldException: No field 'ignoreWIP' found in class 'argelbargel.jenkins.plugins.gitlab_branch_source.settings.GitLabSCMOriginMonitorStrategy', MissingFieldException: No field 'merged' found in class 'argelbargel.jenkins.plugins.gitlab_branch_source.settings.GitLabSCMForksMonitorStrategy', MissingFieldException: No field 'unmerged' found in class 'argelbargel.jenkins.plugins.gitlab_branch_source.settings.GitLabSCMForksMonitorStrategy', MissingFieldException: No field 'ignoreWIP' found in class 'argelbargel.jenkins.plugins.gitlab_branch_source.settings.GitLabSCMForksMonitorStrategy', MissingFieldException: No field 'removeSourceBranch' found in class 'argelbargel.jenkins.plugins.gitlab_branch_source.settings.GitLabSCMForksMonitorStrategy', MissingFieldException: No field 'merged' found in class 'argelbargel.jenkins.plugins.gitlab_branch_source.settings.GitLabSCMTagMonitorStrategy', MissingFieldException: No field 'unmerged' found in class 'argelbargel.jenkins.plugins.gitlab_branch_source.settings.GitLabSCMTagMonitorStrategy', MissingFieldException: No field 'ignoreWIP' found in class 'argelbargel.jenkins.plugins.gitlab_branch_source.settings.GitLabSCMTagMonitorStrategy', MissingFieldException: No field 'onlyMergeable' found in class 'argelbargel.jenkins.plugins.gitlab_branch_source.settings.GitLabSCMTagMonitorStrategy', MissingFieldException: No field 'acceptMergeRequests' found in class 'argelbargel.jenkins.plugins.gitlab_branch_source.settings.GitLabSCMTagMonitorStrategy', MissingFieldException: No field 'removeSourceBranch' found in class 'argelbargel.jenkins.plugins.gitlab_branch_source.settings.GitLabSCMTagMonitorStrategy', MissingFieldException: No field 'buildBranchesWithMergeRequests' found in class 'argelbargel.jenkins.plugins.gitlab_branch_source.settings.GitLabSCMSourceSettings', MissingFieldException: No field 'listenToWebHooks' found in class 'argelbargel.jenkins.plugins.gitlab_branch_source.settings.GitLabSCMSourceSettings', MissingFieldException: No field 'registerWebHooks' found in class 'argelbargel.jenkins.plugins.gitlab_branch_source.settings.GitLabSCMSourceSettings'

**Comment by Argelbargel** [comment]
@i386: could you have a look at [0.7.5-dev](https://github.com/Argelbargel/gitlab-branch-source-plugin/releases/tag/0.7.5-dev) and check if single SCMSources work?

**Comment by grfullerton** [comment]
@Argelbargel I've been able to use Multibranch Pipelines with this plugin without issue.
