### ISSUE TITLE
Marking of MR jobs as (merged) seems a bit aggressive

### ISSUE THREAD

**Issue by ananace** [Argelbargel/gitlab-branch-source-plugin#20]
As seen on this picture, the MR is certainly not merged yet.

![screenshot_20170519_155552](https://cloud.githubusercontent.com/assets/534460/26250876/c2fb24c4-3cab-11e7-8a80-febb49a82778.png)

**Comment by Argelbargel** [comment]
Okay :-) It is not meant that way. (merged) should indicate, that this job builds the changes of the merge-request merged into the target branch vs the unmarked job which builds the source-branch of the merge-request as it is. 

What do you think would be a better wording?

**Comment by ace13** [comment]
Ahh, that wording would definitely need to be updated indeed. Perhaps put a
more detailed sentence in the description of the MR job?

**Comment by Argelbargel** [comment]
For now, i've just removed the 'd' ;-)

**Comment by ace13** [comment]
(merge) would certainly be less confusing.

I still feel like this should be written somewhere outside of the job title
for the best result though.
The correct wording would no doubt be too long to stick into a set of
parentheses after all.

On 19 May 2017 6:34 pm, "Karsten Kraus" <notifications@github.com> wrote:

For now, i've just removed the 'd' ;-)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Argelbargel/gitlab-branch-source-plugin/issues/20#issuecomment-302751091>,
or mute the thread

**Comment by Argelbargel** [comment]
I think there has some difference in the names as both jobs are shown in the same view (the tabs are only ui-sugar as far as i understand it). So (merge) or (m) or something like that will have to be. I'll see if i find a way to add a longer explanation to the jobs description.

**Comment by ace13** [comment]
Is there any way to do the merge both merged against the branch and as a loose head at the same time?

I thought you had to choose between one or the other, so where would the collision be - if that's the concern?

**Comment by Argelbargel** [comment]
Yes, you can enable the building of both the merged and unmerged heads in the advanced options.

**Comment by ace13** [comment]
Ah, I thought that checkbox was for choosing between merged and unmerged head, not for choosing if you want both or only merged.

Probably best to improve the wording of that option as well.
"Build unmerged head" sounds very definite, and the description does nothing to dissuade that thought.

**Comment by Argelbargel** [comment]
Okay, i get your issue. I wanted to name the plugin's options accordingly to the respective options in the github-branch-plugin. The help-descriptions were partly my own though and my english is not fluent enough in all situations ;-) I've now changed them to more closely match those of the github-branch-plugin.

Keeping this open though - perhaps we'll find some better namings and descriptions together...
