### ISSUE TITLE
Wrong name for MR in blue ocean

### ISSUE THREAD

**Issue by lainosantos** [Argelbargel/gitlab-branch-source-plugin#31]
In the blue ocean pull request view, the merge request name is displaying as an integer number, most likely a sequential id.

**Comment by lainosantos** [comment]
Too.. summary and author are empty.

**Comment by Argelbargel** [comment]
Hi @lainosantos,

thank you for your feedback. Great that there's someone trying out the plugin with blue-ocean (i'm assuming, you're using the current 0.7-dev version?). 
I am currently in heavily swamped in work at my day job, so it might take some time to check on your issues. 

It would be great if you could post screenshots for your issues and the version of the blue-ocean-plugin you use to make it easier for me to spot where the bugs are hiding.

Kind regards

Argelbargel

**Comment by lainosantos** [comment]
Hi @Argelbargel , congratulations to you for this great plugin.

I'm using Blue Ocean at version 1.1.4.

![image](https://user-images.githubusercontent.com/8415575/27906402-c53bc93a-6219-11e7-88b2-eb2fe436133c.png)
