### ISSUE TITLE
Internal project naming

### ISSUE THREAD

**Issue by luisbrandao** [Argelbargel/gitlab-branch-source-plugin#35]
Hi,

I have a gitlab and a github repo, both with organization plug-ins.
In github, inside the organization, the repo names are plain: 
agent
site
rest

however in the gitlab Organization, a "full path" is show:
myorg/agent
myorg/site
myorg/rest

this "my org" in the repo name, breaks the var ${env.BRANCH_NAME}, since its get "myorg/site" instead "site"

**Comment by Argelbargel** [comment]
Hmm... I'll look into it (but am swamped at work until the end of july)
Could you post a screeenshot or a summary of the settings of the gitlab-organisation settings in jenkins? E.g. are you restricting the projects to poll by group etc.?

**Comment by luisbrandao** [comment]
![captura de tela de 2017-07-14 13-22-21](https://user-images.githubusercontent.com/25795753/28221066-4270fd24-6898-11e7-83d8-667f8d0b8c28.png)
![captura de tela de 2017-07-14 13-22-36](https://user-images.githubusercontent.com/25795753/28221068-447322d2-6898-11e7-80a2-4af8d7d9ab36.png)

**Comment by Argelbargel** [comment]
Oh. Sorry, i meant the settings behind the "configure" link of the gitlab-organisation.

**Comment by luisbrandao** [comment]
![captura de tela de 2017-07-14 13-30-06](https://user-images.githubusercontent.com/25795753/28221216-d3da905e-6898-11e7-8ccf-10a25707c56a.png)

**Comment by luisbrandao** [comment]
Sorry, i missread. I only understand the question on the second time i read it XD

**Comment by Argelbargel** [comment]
No problem ;-). Your using the restriction to a group - then this should be easy to fix. Are you using the 0.7-dev or the 0.6.x release?

**Comment by luisbrandao** [comment]
latest: 0.6.4.1
