### ISSUE TITLE
Credentials for Git checkout not saved on dev-0.7

### ISSUE THREAD

**Issue by Aeon512** [Argelbargel/gitlab-branch-source-plugin#38]
Hi,
the checkout credentials are not saved when configuring git checkout.
After saving and re-opening the configuration screen it falls-back to "Anonymous".

Manually changing the job XML configuration <credentialsId> works though.

Thanks for the great plugin
/Aeon512

**Comment by smutel** [comment]
Hello,

I think that it's linked but ...
The credentials are not populated to the job. So I got this error:
> stderr: fatal: Authentication failed for 'xxxx'

@Aeon512 Could you please give details of your workaround?

Thanks.

**Comment by Aeon512** [comment]
@smutel: Make your Change, configure you job. Save. Now open the XML file corresponding to your job in the Jenkins Jobs folder on your hard disc and edit the gitlab section. In particular fill out the missing credentialsId. 
Save the XML and in Jenkins Manage reload the configuration from disc.

**Comment by tostt** [comment]
With version 0.7.3-dev, every time I hit "save" in the configuration screen, the XML gets written with `<credentialsId>ANONYMOUS</credentialsId>`, overwriting whatever happens to be there.

This means that every time you change the job configuration, you have to edit and reload the XML.
And even if the XML has a correct <credentialsId> and I reload the config from files, I still get the error :  Authentication failed for xxx.

Note that the credentials in the Pipeline Libraries section do stick when saved, as expected.

**Comment by derTobsch** [comment]
We have the same problem.

**Comment by tostt** [comment]
I did some more testing. If the git plugin section is correctly configured, it doesn"t seem to be a problem that the GitLab-Connection checkout credentials are reset to anonymous. But I notice that other settings are reset too. In my case, the "Monitor Tags" and "Build Tags" (in the "Monitoring & Build-Strategy" section) are reset too, which prevents me from triggering releases on new tags.

**Comment by frznlogic** [comment]
+1. We have this same issue on the 0.7-dev branch.

**Comment by Argelbargel** [comment]
Hi guys, credentials and other settings should be fixed with [0.7.5-dev](https://github.com/Argelbargel/gitlab-branch-source-plugin/releases/tag/0.7.5-dev)

**Comment by tostt** [comment]
The problem is solved, thank you for fixing it.

**Comment by frznlogic** [comment]
Confirmed, it's fixed :)
