### ISSUE TITLE
Add a Project selector for 'member'

### ISSUE THREAD

**Issue by ace13** [Argelbargel/gitlab-branch-source-plugin#4]
So that it only lists the projects which the Jenkins user is a member of.

**Comment by Argelbargel** [comment]
Do you mean the user currently logged into jenkins or the user used to connect to gitlab?

**Comment by ace13** [comment]
The Jenkins user for the Gitlab connection.

Our Gitlab instance already has the Jenkins user as a member of all
projects where builds are to happen, since Jenkins requires developer
rights to publish build results and such.
Would be very helpful if we could keep that integration, so all that people
need to do is add Jenkins as a developer on their projects to get builds
running.

On 2 Mar 2017 10:44 am, "Karsten Kraus" <notifications@github.com> wrote:

Do you mean the user currently logged into jenkins or the user used to
connect to gitlab?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Argelbargel/gitlab-branch-source-plugin/issues/4#issuecomment-283605591>,
or mute the thread

**Comment by Argelbargel** [comment]
Hmmm... i'look into it, but this should work right now when you set the project selector to "visible". The Gitlab-API only lists those project where the current user is a member of (or a member of the group of the project); even the root user or a user with admin role cannot list/see projects he is not a member of (i'm using this endpoint when scanning for projects: https://docs.gitlab.com/ee/api/projects.html#list-projects).

Could you send me a screenshot of the plugin-configuration in jenkins? And which version of gitlab do you use? Perhaps the api works differently there?

**Comment by ace13** [comment]
You know, it's actually possible that this already works the way it should - just that we have too many projects for it to manage properly.
Seem to have another issue though with the scan breaking partway through on a 403 error, so that could certainly help make it look wrong.

Guess you can close this issue.

**Comment by Argelbargel** [comment]
Oh. Well i am not rate-limiting the connection right now - so yes this could be the real culprit. Could you confirm this? E.g. by restricting the amount of projects by pattern? We have around 20 projects currently and this works but perhaps if there are more than x projects it breaks down?

Another reason could be that i'm trying to do something which the user is not allowed to do with developer rights. could you open another issue and include an excerpt of the scan-log there?
