### ISSUE TITLE
Sub Groups are missing after Scan

### ISSUE THREAD

**Issue by awilhelmer** [Argelbargel/gitlab-branch-source-plugin#40]
When a group has a Subgroup, e.g. "group/sub-groub/", the sub group of gitlab isn't scanned or found.
Explicit scans doesnt work too. I tried "sub-group" and "group/sub-groub" but both doesnt find anything.

**Comment by awilhelmer** [comment]
I found a solution. You have to enter the ID (number) of the group, then it is working. 
The ID can be accessed with the API:
`curl -H "Content-Type: application/json" -H "PRIVATE-TOKEN: TOKEN" https://gitlab.com/api/v4/groups`

**Comment by frznlogic** [comment]
We have the same issue :). According to some testing my colleagues did, it's possible that the issue is within gitlab itself though. Doing the "correct" search pattern directly against the gitlab api turns up an empty set.
