### ISSUE TITLE
Add Ability for Parameterized builds

### ISSUE THREAD

**Issue by Blacksheep92** [Argelbargel/gitlab-branch-source-plugin#41]
Hey, 
it would be nice if you can add some parameter from the gitlab merge request hook to the build environment.

e.g.:
- gitlabMergeRequestId
- gitlabSourceNamespace
- gitlabSourceBranch
- gitlabSourceRepoSshURL
- gitlabTargetNamespace
- gitlabTargetBranch
- gitlabTargetRepoSshURL

**Comment by Argelbargel** [comment]
Hi, i've just released 0.6.5 which should add the information of the hooks to the build's environment.
