### ISSUE TITLE
Master does not build (different problems)

### ISSUE THREAD

**Issue by derTobsch** [Argelbargel/gitlab-branch-source-plugin#51]
Hey, 
first of all I really like this projects as far as I know it :) But there are two major problems why the master does not build.

**First**
You are using AbstractGitSCMSource#isExcluded in `GitLabSCMSource` that is deprecated since 3.4.0
and you are using

```xml
        <dependency>
            <groupId>org.jenkins-ci.plugins</groupId>
            <artifactId>git</artifactId>
            <version>3.4.1</version>
        </dependency>
```
and now the enforcer will stop the build from working.

**Second**
You are using the class `import org.jenkinsci.plugins.workflow.steps.FlowInterruptedException` in `GitLabSCMPublishAction` since 63eaab7 but that class is only defined in the test classpath as you can see in the pom

```xml
        <dependency>
            <groupId>org.jenkins-ci.plugins.workflow</groupId>
            <artifactId>workflow-step-api</artifactId>
            <version>2.12</version>
            <scope>test</scope>
        </dependency>
```

These two major problems. 

We would like to use this plugin and tried the latest 0.6.x.x version and the latest 0.7.x-dev version but as far as we got a feeling its at this time not usable in a production environment. But I would like to help to get it there, and I think its not far away.

I read your issues and comments that you would like to merge it with the gitlab plugin, is that the plan?
Maybe first things first and we stabilise the 'independent' plugin and later merge it? So it could provide some benefit to the community.

I would like to here from you and your ideas.

**Comment by Argelbargel** [comment]
Hi @derTobsch ,

ouch, this should not be. To be honest, i could not spent much time on this project in the last month as it gets either stalled by me spending time moving and furnishing my new flat or by my working hours extending in the evenings. 

Thus the state of master is, well, not good. I'll see that i get it in a state that it least builds again sometime soon. Until then you could try building the release branch (that branch is the base for the version i'm using at work so it should at least build, but it's missing the possiblity to use GitLabSCMSource standalone) or the 0.7-dev branch. Those should at least built (well, they do on travis-ci.org -> https://travis-ci.org/Argelbargel/gitlab-branch-source-plugin).

If you'd like to participate in this project and have some time at your hands that would be great :-)

**Comment by derTobsch** [comment]
Hey sorry that it took so long. I have a new project at my company :) I think you know what that means. But we have a "Slack" Friday and I am planning to look into this plugin in the next weeks.

@Argelbargel you live in Baden-Baden or? I am working in Karlsruhe so maybe we could meet in person and hack this plugin? :)

**Comment by frznlogic** [comment]
Hi @derTobsch , I think this has been solved in the latest 0.7-dev branch/tags? It builds fine for me at least right now ;)

**Comment by derTobsch** [comment]
@frznlogic than we should merge this into master? :)

**Comment by Argelbargel** [comment]
Hi guys,

just some short info about the structure of the project:

- branch release contains the "stable" branch which we use at work and which was quickly adopted as soon as i published the project. i try to make only minor changes here to keep it backwards-compatible
- 0.7-dev began life as a feature-branch for #18. For this a reworked the way the settings are managed (and obviously broke them)
- master is the branch i've played in and tried to do some preliminary work to begin merging this plugin with the gitlab-plugin. Did not make much headway there and let it broken as it is when i did not have any more time to spare

I'll merge/replace the current master branch with 0.7-dev this weekend so that we at least have a mostly working state there to go on with...

**Comment by Argelbargel** [comment]
@derTobsch: yes, i live in Baden-Baden. Meeting in person would be nice. I've got a release coming up at work in the first week of april, so i'm not sure that i've got the time this month. But i'll see what i can do and will send you an email...

**Comment by Argelbargel** [comment]
Ok. The former 0.7-dev branch is now the master branch. 0.7-dev was removed. so now master is building again.
