### ISSUE TITLE
0.7.4-dev - Authentication info are not saved

### ISSUE THREAD

**Issue by martinotu** [Argelbargel/gitlab-branch-source-plugin#55]
Hi, 

let me tell you how happy am I to have found this project! ;-)

I tried it immediately as this will fix a lot of issues I am having with jenkins-gitlab integration but unfortunately the "Checkout credentials" inside "GitLab-Connection"are not saved and I cannot checkout!

Hope this will be fixed soon and thanks again for the amazing work!

Mt.
<img width="693" alt="screen shot 2018-03-01 at 16 01 42" src="https://user-images.githubusercontent.com/534575/36851711-2d9d78aa-1d6a-11e8-99e8-40a3539c9a64.png">

**Comment by Argelbargel** [comment]
please see #38. should be fixed with [0.7.5-dev](https://github.com/Argelbargel/gitlab-branch-source-plugin/releases/tag/0.7.5-dev)

**Comment by martinotu** [comment]
Thanks!

Verified to work on 0.7.5-dev
