### ISSUE TITLE
Gitlab-Pipeline is not updated when build fails

### ISSUE THREAD

**Issue by Argelbargel** [Argelbargel/gitlab-branch-source-plugin#56]
According to @martinotu's comment in #45:

I trie it but the dev-release doesn't update gitlab when there is a
failure. So all the jobs are green even if there is a failure.

**Comment by martinotu** [comment]
Any update on this?

**Comment by smutel** [comment]
Have the same issue ...

**Comment by frznlogic** [comment]
Same issue.
