### ISSUE TITLE
Support note events

### ISSUE THREAD

**Issue by ananace** [Argelbargel/gitlab-branch-source-plugin#6]
Our current setup uses the note event to do conditional builds in Jenkins, something that I'm noticing is lacking on here.

For instance;
```groovy
if (env.gitlabActionType == 'MERGE' && env.gitlabTriggerPhrase.contains('debug')) {
  echo 'Debug data:'
  sh 'df -h | grep home && free -m && ls -l && env'
}
```

Which in turn means that you can respond to a merge request with something like `@jenkins: debug` to get a rebuild with additional debugging information to try and help figure out why it's broken.

**Comment by Argelbargel** [comment]
I didn't implement note event for the sole reason that I don't like them :-) I think, commit-messages should tell users/other developers about changes in the code and should not be used to trigger functionality. 

As the Gitlab-plugin supports them and they're convenient in some situations, whatever I think, I'll look into it. As the basic support is already present this should not be hard to implement.
