### ISSUE TITLE
/ replaced by %2F in JOB_NAME

### ISSUE THREAD

**Issue by smutel** [Argelbargel/gitlab-branch-source-plugin#62]
Hello,

/ are replaced by %2F in the folder name.

We can see this here:
![image](https://user-images.githubusercontent.com/12967891/38364271-2f565638-38d8-11e8-8c20-71b334409d56.png)

Or in the pipeline, in the JOB_NAME variable, we can have also %2F to separate GITLAB group.
I checked the current issues but I didn't find any issue related to this.

In this case the split function with character '/' to retrieve only the job name does not work ...

Thanks.

**Comment by Argelbargel** [comment]
I know. I develop the plugin for the older gitlab-version we're using at work which does not support sub-groups. I'll try to add sub-group-support or at least fix the name-display...

**Comment by smutel** [comment]
Workaround is useful for me, thanks.
