### ISSUE TITLE
Webhooks not setup automatically

### ISSUE THREAD

**Issue by smutel** [Argelbargel/gitlab-branch-source-plugin#63]
Hello,

Could you please give me some information on this topic:
1. What is the prerequisites for the plugin to setup the webhooks automatically (version of GITLAB, user permission, ...) ?
2. How to troubleshoot ?
3. Can I setup the webhook manually and how?

Thanks.

**Comment by grfullerton** [comment]
1. I'm pretty sure any "Master" or "Owner" can setup webhooks.  So if the Gitlab Access Token used in Jenkins is either of these, the webhooks can be setup automatically, as far as I know. I'm not sure about Gitlab version

2. In gitlab, if you go to a Project > Settings > Integrations, you'll be able to see existing webhooks, they should be listed below the form to add a new webhook.  The URL will look something like https://YOUR_JENKINS_URL/gitlab-scm/notify/SOME_HASH.  To test that the webhook is working, click on the "Test" button. If everything worked, you should see a "Hook executed successfully: HTTP 200" message.

3. To setup the webhook manually, in your jenkins job config, look for a "Webhooks" section.  If you click "Advanced", you'll see  "Auto-Register Webhook", which will be checked by default.  Uncheck it, and a URL will be displayed. Using that URL, you can go to the integrations page in gitlab, as I explained in Question 2, and paste the URL.  Then select all the hooks you want to notify jenkins, and click "Add webhook".  You can test the manual webhook just like the automatic one.

**Comment by smutel** [comment]
Thanks for this information.
Stupid I am ... jenkins user was reporter ... now it works fine.
