### ISSUE TITLE
MergeRequest does not trigger build

### ISSUE THREAD

**Issue by ghost** [Argelbargel/gitlab-branch-source-plugin#70]
Hello,

I'm running Jenkins 2.89.4, Gitlab 9.1.0, Jenkins Gitlab Plugin 1.5.5 and Gitlab Branch Source plugin from source.
I'm able to add a new project in Jenkings, build are triggered when I push on branches but when I create a Merge Request nothing happen. How can I debug this and/or provide more useful informations ?

**Comment by ilushka85** [comment]
I have a pr that fixes this.....

**Comment by bartse** [comment]
I can confirm regular push events are not picked up any more from 0.6.7
I had to downgrade to version 0.6.6.6 to have this working again(events are received when checking the events log but no actual job is being triggered)
