### ISSUE TITLE
Posting more result metadata to GitLab

### ISSUE THREAD

**Issue by mardy** [Argelbargel/gitlab-branch-source-plugin#76]
Hi!
  We are currently using this plugin and reporting build information (stages, and final success/failure result) back into GitLab. However, I couldn't find a way to pass extra data, such as coverage results.

Is it possible to somehow pass an extra string of information back to GitLab? I could use it to write the percentage of code coverage, or maybe a link to the artifact file where this information can be found.

**Comment by acarmel** [comment]
You can use the 'addGitLabMRComment' step
```
post {
  always {
    addGitLabMRComment comment: "[coverage report link](coverage report_url)"
}
```


[Gilab Plugin Steps](https://jenkins.io/doc/pipeline/steps/gitlab-plugin/#code-addgitlabmrcomment-code-add-comment-on-gitlab-merge-request)

**Comment by mardy** [comment]
Thanks, this will perfectly cover my needs!
