### ISSUE TITLE
Finished organization scan. Finished: NOT_BUILT

### ISSUE THREAD

**Issue by alexkoepke** [Argelbargel/gitlab-branch-source-plugin#83]
```
Started
[Tue Jun 26 11:31:31 EDT 2018] Starting organization scan...
[Tue Jun 26 11:31:31 EDT 2018] Updating actions...
Started [Tue Jun 26 11:3
[Tue Jun 26 11:31:37 EDT 2018] Consulting GitLab Projects
Retrieving projects for [redacted]...
[Tue Jun 26 11:31:37 EDT 2018] Finished organization scan. Scan took 6.6 sec
Finished: NOT_BUILT
```

Jenkins: `2.121.1`
GitLab Branch Source Plugin: `0.6.6.6` and `0.6.7`
GitLab: `11.0.1-ce.0`

Not sure where to look for more errors. Thanks in advance.

**Comment by VFUC** [comment]
GitLab API v3 has been removed in GitLab 11.0 - this might cause these issues ?

**Comment by lifeofguenter** [comment]
same issue with `Jenkins ver. 2.138.3` + `gitlab branch: 0.6.6.6` + `gitlab plugin: 1.5.10` + gitlab.com (e.g. latest)
