### ISSUE TITLE
Plugin is lacking a security contact

### ISSUE THREAD

**Issue by daniel-beck** [Argelbargel/gitlab-branch-source-plugin#88]
It is unclear what the security contact (or security issue reporting policy in general) of this plugin is.

**Comment by Argelbargel** [comment]
Hmmm. What do you mean exactly? You've found a security-related problem which you do not want to create an issue for?

**Comment by daniel-beck** [comment]
It's unclear what the process should be. If you want security vulnerabilities to be reported openly, that's fine, but that's not stated either.

**Comment by Argelbargel** [comment]
Hmm. Did not think about this yet. As this is basically just a private github repo and the plugin is not distributed via the jenkins-update-site (yet), i'd like to keep it simple without an extra mail-account and such. On the other hand, as i do not have much time currently to do fixes for this, public security-related issues would make users vulnerable. I'll think about it and come back to you...
