### ISSUE TITLE
doesn't build pushes

### ISSUE THREAD

**Issue by timurb** [Argelbargel/gitlab-branch-source-plugin#90]
I can't make the plugin do the builds on common pushes.

Merge requests are built fine when created and updated.
Pushes and removal of  merge requests are not -- they show up in logs but no action is taken in Jenkins.
If I click "Scan Gitlab Project Now" everything goes as expected (builds happen when needed and old MRs are removed) but I'd want to avoid polling.

Any ideas what could be wrong? Is it a bug in plugin/jenkins or my incorrect setup somewhere?

Here is the loglines that I see in `GitLab Project Events` when I do push in Gitlab repo:
```
[Sun Jul 29 05:27:03 UTC 2018] Received argelbargel.jenkins.plugins.gitlab_branch_source.events.GitLabSCMPushEvent UPDATED event from 52.91.128.129 ⇒ http://jenkins.xxxxxxx:8080/gitlab-scm/notify/f9abb9efa9fff10b8646a397c5370301/2 with timestamp Sun Jul 29 05:27:03 UTC 2018
Retrieving heads for project root/timur...
Retrieving branch master...
Monitoring branch master
      ‘Jenkinsfile’ found
master (d597591a13d2cb4fae7ff00f1e8f78544fade78c) meets criteria
[Sun Jul 29 05:27:03 UTC 2018] argelbargel.jenkins.plugins.gitlab_branch_source.events.GitLabSCMPushEvent UPDATED event from 52.91.128.129 ⇒ http://jenkins.xxxxxxx:8080/gitlab-scm/notify/f9abb9efa9fff10b8646a397c5370301/2 with timestamp Sun Jul 29 05:27:03 UTC 2018 processed in 37 ms
```

Here are the few settings in build job for Gitlab in Jenkins that could be relevant:
<img width="472" alt="gitlab config jenkins 2018-07-29 00-32-16" src="https://user-images.githubusercontent.com/209945/43363278-1ab8a64c-92c7-11e8-95e9-c4671ab30379.png">
<img width="473" alt="gitlab config jenkins 2018-07-29 00-32-57" src="https://user-images.githubusercontent.com/209945/43363280-21ca0282-92c7-11e8-9a97-21e16c36219c.png">
<img width="471" alt="gitlab config jenkins 2018-07-29 00-33-17" src="https://user-images.githubusercontent.com/209945/43363281-2aaca152-92c7-11e8-8996-0cf41e902ddf.png">

I have the following versions:
- Jenkins ver. 2.107.3
- branch API 2.0.20
- credentials 2.1.16
- folders 6.4
- git 3.9.0
- git-client 2.7.2
- gitlab 1.5.8
- gitlab-branch-source 0.6.7
- scm-api 2.2.7
and pipeline plugins released with that version of Jenkins (pipeline-api is 2.27)

Is there some issue with plugin or do I have some kind of misconfiguration?

**Comment by Argelbargel** [comment]
Hi, did you try if it works with 0.6.6? This is the last release which i confirmed as working at least for me. 0.6.7 was a release to check/test a pr and should be marked as pre-release. I know, that is not perfect but currently i've got little time to maintain this project...

**Comment by timurb** [comment]
Yes, in 0.6.6.6 this apparently works. Thank you for a quick response!
