### ISSUE TITLE
Branch deleted after creating a merge request

### ISSUE THREAD

**Issue by ghost** [Argelbargel/gitlab-branch-source-plugin#92]
Hi,

When I create a merge request in gitlab the source branch is "deleted" in Jenkins (his name is strikethrough) and I'm not able to trigger the build of that branch anymore. If I remove the branch in Jenkins the branch is re-created but I need to manually run the build

**Comment by jcgleissner** [comment]
@ghost do you still have this issue? Did you find a way to resolve it?
We're facing exactly that issue on version 0.7.3-dev.
We've suspected that as soon as there are more than 50 Branches loaded, some branches randomly will be disabled.

**Comment by Argelbargel** [comment]
Hi. Could you try if the new gitlab-branch-source-plugin (https://plugins.jenkins.io/gitlab-branch-source) fixes this issue? As the company i work for is itself switching to that plugin, i most probably will not make any changes the the code of this plugin (not that i've spent much time on it in the past year in any case :-/)
