### ISSUE TITLE
Cannot use a custom build strategy 

### ISSUE THREAD

**Issue by ghost** [Argelbargel/gitlab-branch-source-plugin#94]
Hi !

I want to add the capability to not trigger a build based on the commit Author. This feature is not implemented in this plugin so I've installed the [ignore-committer-strategy-plugin](https://github.com/jenkinsci/ignore-committer-strategy-plugin) and added his provided Build strategy in a Gitlab Project. The build strategy is executed (I can see this in the Jenkins log) but the build is trigger and executed regardless of the author.
I don't know if it's a bug, I don't know if it's related to the gitlab plugin, the github branch plugin or this gitlab-branch-source-plugin.

How does this plugins interacts ? And where is the decision taken to trigger a build or not ? If it's not possible to use a "custom" branch strategy where can I add this behaviour in the gitlab-branch-source-plugin ?

**Comment by Argelbargel** [comment]
Hi. Could you check, whether the new gitlab-branch-source-plugin (see https://plugins.jenkins.io/gitlab-branch-source) plays more nicely with custom build-strategies? 
With the advent of the new (much better supported) plugin, i most probably will not make any relevant changes to the code of this plugin
