### ISSUE TITLE
Mistakes in readme

### ISSUE THREAD

**Issue by serge2016** [Argelbargel/gitlab-branch-source-plugin#95]
Hello!
When I check dependencies I can't find several of them. So I suggest to replace them with:
cloudbees-folder 6.0.3 --> Folders Plugin (https://wiki.jenkins.io/display/JENKINS/CloudBees+Folders+Plugin)
workflow-api 2.12 --> Pipeline: API (https://wiki.jenkins.io/display/JENKINS/Pipeline+API+Plugin)
workflow-cps 2.29 --> Pipeline: Groovy (https://wiki.jenkins.io/display/JENKINS/Pipeline+Groovy+Plugin)
workflow-job 2.10 --> Pipeline: Job (https://wiki.jenkins.io/display/JENKINS/Pipeline+Job+Plugin)
workflow-multibranch 2.12 --> Pipeline: Multibranch (https://wiki.jenkins.io/display/JENKINS/Pipeline+Multibranch+Plugin)

**Comment by daniel-beck** [comment]
Preferred plugin URLs are now at plugins.jenkins.io.

**Comment by serge2016** [comment]
@daniel-beck 
My question is about readme.md in this repository. I thank the readme should be corrected.

**Comment by daniel-beck** [comment]
I understand that. To clarify:
You write: https://wiki.jenkins.io/display/JENKINS/CloudBees+Folders+Plugin
I propose: https://plugins.jenkins.io/cloudbees-folder

**Comment by serge2016** [comment]
@daniel-beck 
Oh, I see! This is a great idea!

**Comment by Argelbargel** [comment]
Hi. With the advent of the new gitlab-branch-source-plugin (see https://plugins.jenkins.io/gitlab-branch-source), i will most probably not make any changes to the code of this plugin.

**Comment by daniel-beck** [comment]
@Argelbargel Time to archive this repo then to make it clear to users?

**Comment by Argelbargel** [comment]
Great idea! Did not know one could do this. I'll do that right away! Thanks ;-)
