### ISSUE TITLE
Restrict users from creating job with empty filter

### ISSUE THREAD

**Issue by timurb** [Argelbargel/gitlab-branch-source-plugin#96]
It would be great if we could in some way restrict users from creating Gitlab branch source job with empty filter (blank group ID, etc).

When the job is created it triggers the whole organization scan and a build queue of few dozens of projects.

**Comment by Argelbargel** [comment]
Hi. Could you try if the new gitlab-branch-source-plugin (https://plugins.jenkins.io/gitlab-branch-source) fixes this issue? As the company i work for is itself switching to that plugin, i most probably will not make any changes the the code of this plugin (not that i've spent much time on it in the past year in any case :-/)
