### ISSUE TITLE
Prevent plugin from renaming the project

### ISSUE THREAD

**Issue by matejdro** [Argelbargel/gitlab-branch-source-plugin#98]
Right now it appears that adding "Gitlab Project" source to Multibranch project will also rename the jenkins project to the name of the Gitlab project. Is there a way to prevent this?

**Comment by Argelbargel** [comment]
Hi. Could you try if the new gitlab-branch-source-plugin (https://plugins.jenkins.io/gitlab-branch-source) fixes this issue? As the company i work for is itself switching to that plugin, i most probably will not make any changes the the code of this plugin (not that i've spent much time on it in the past year in any case :-/)
