### ISSUE TITLE
"Monitor & Build Origin Branches" cannot be disabled

### ISSUE THREAD

**Issue by matejdro** [Argelbargel/gitlab-branch-source-plugin#99]
I want my Jenkins to only build branches that have MR. But it appears that "Monitor & Build Origin Branches" option is always active, even when unchecked in settings.

It seems like regardless of the state of this option, plugin will start to build branches that are not part of any merge requests.

As a workaround, I have added this to my `Jenkinsfile`:

```groovy
    if (env.gitlabActionType != "MERGE") {
        currentBuild.result = 'NOT_BUILT'
        error("Aborting build without Merge Request ($env.gitlabActionType)")
    }
```

**Comment by guillaumelecerf** [comment]
Fixed in https://github.com/Argelbargel/gitlab-branch-source-plugin/pull/104/files

**Comment by Argelbargel** [comment]
@matejdro: as @guillaumelecerf fixed this, i'm closing here...
